### ISSUE TITLE
Calling `Function::bind` on an async function causes reference leak

### ISSUE THREAD

**Issue by hackerer1c** [khvzak/mlua#161]
mlua: `master` branch, commit `6b2ceb60`
rustc: 1.60.0 stable
Features: `["lua54", "async", "macros", "serialize"]`

Reproduction:

```rust
// src/main.rs
use mlua::{Lua, Table};

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
  let lua = Lua::new();

  let f1 = lua.create_async_function(|_lua, context: Table| async move {
    tokio::fs::File::open("Cargo.toml").await?;
    context.raw_get::<_, mlua::Value>("foo")
  })?;

  let context = lua.create_table()?;
  context.raw_set("foo", "bar")?;

  let f2 = f1.bind(context)?;

  f2.call_async(()).await?;

  Ok(())
}
```

```console
$ cargo run
thread 'main' panicked at 'mlua internal error: reference leak detected (this is a bug, please file an issue)', /Users/hacker/.cargo/git/checkouts/mlua-4fd10c345875f70c/6b2ceb6/src/lua.rs:258:13
stack backtrace:
   0: std::panicking::begin_panic
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:616:12
   1: <mlua::lua::LuaInner as core::ops::drop::Drop>::drop
             at /Users/hacker/.cargo/git/checkouts/mlua-4fd10c345875f70c/6b2ceb6/src/lua.rs:258:13
   2: core::ptr::drop_in_place<mlua::lua::LuaInner>
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ptr/mod.rs:188:1
   3: core::ptr::drop_in_place<core::cell::UnsafeCell<mlua::lua::LuaInner>>
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ptr/mod.rs:188:1
   4: alloc::sync::Arc<T>::drop_slow
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/sync.rs:1092:18
   5: <alloc::sync::Arc<T> as core::ops::drop::Drop>::drop
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/sync.rs:1688:13
   6: core::ptr::drop_in_place<alloc::sync::Arc<core::cell::UnsafeCell<mlua::lua::LuaInner>>>
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ptr/mod.rs:188:1
   7: core::ptr::drop_in_place<mlua::lua::Lua>
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ptr/mod.rs:188:1
   8: test_mlua::main::{{closure}}
             at ./src/main.rs:20:1
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  10: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /Users/hacker/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.18.2/src/park/thread.rs:263:54
  11: tokio::coop::with_budget::{{closure}}
             at /Users/hacker/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.18.2/src/coop.rs:102:9
  12: std::thread::local::LocalKey<T>::try_with
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/thread/local.rs:413:16
  13: std::thread::local::LocalKey<T>::with
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/thread/local.rs:389:9
  14: tokio::coop::with_budget
             at /Users/hacker/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.18.2/src/coop.rs:95:5
  15: tokio::coop::budget
             at /Users/hacker/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.18.2/src/coop.rs:72:5
  16: tokio::park::thread::CachedParkThread::block_on
             at /Users/hacker/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.18.2/src/park/thread.rs:263:31
  17: tokio::runtime::enter::Enter::block_on
             at /Users/hacker/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.18.2/src/runtime/enter.rs:151:13
  18: tokio::runtime::thread_pool::ThreadPool::block_on
             at /Users/hacker/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.18.2/src/runtime/thread_pool/mod.rs:81:9
  19: tokio::runtime::Runtime::block_on
             at /Users/hacker/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.18.2/src/runtime/mod.rs:477:43
  20: test_mlua::main
             at ./src/main.rs:19:3
  21: core::ops::function::FnOnce::call_once
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by khvzak** [comment]
Fixed, thanks.
I also found that the previous implementation was useless for async functions, as Lua cannot yield across C-call boundary.
Which is fixed too.
