### ISSUE TITLE
Fail to compile example in the homepage https://crates.io/crates/mlua on windows 10

### ISSUE THREAD

**Issue by flyinmind** [khvzak/mlua#22]
**Cargo.toml:**
[dependencies]
mlua = {version = "0.4", features = ["luajit"]}
mlua_derive = "0.4"

Any suggestions? Thanks!

**Error information:**
error: failed to run custom build command for `mlua v0.4.2`
Caused by:
  process didn't exit successfully: `xxx\target\release\build\mlua-3f46c0cec6ba759a\build-script-main` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=LUA_INC
  cargo:rerun-if-env-changed=LUA_LIB
  cargo:rerun-if-env-changed=LUA_LIB_NAME
  cargo:rerun-if-env-changed=LUA_LINK
  cargo:rerun-if-env-changed=LUAJIT_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=LUAJIT_STATIC
  cargo:rerun-if-env-changed=LUAJIT_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-pc-windows-msvc
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_pc_windows_msvc
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-pc-windows-msvc
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_pc_windows_msvc
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-pc-windows-msvc
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_pc_windows_msvc
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Command { command: "\"pkg-config\" \"--libs\" \"--cflags\" \"luajit\" \"luajit >= 2.0.5\"", cause: Os { code: 2, kind: NotFound, message: "系统找不到指定的文件(System cant't find the file)" } }', d:\Tools\rust\\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-ed15b681fafda09b\mlua-0.4.2\build\find_normal.rs:100:13
  stack backtrace:
     0:     0x7ff795a97d29 - std::backtrace_rs::backtrace::dbghelp::trace
                                 at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
     1:     0x7ff795a97d29 - std::backtrace_rs::backtrace::trace_unsynchronized
                                 at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
     2:     0x7ff795a97d29 - std::sys_common::backtrace::_print_fmt
                                 at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\sys_common\backtrace.rs:79
     3:     0x7ff795a97d29 - std::sys_common::backtrace::_print::{{impl}}::fmt
                                 at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\sys_common\backtrace.rs:58
     4:     0x7ff795aaedbb - core::fmt::write
                                 at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\core\src\fmt\mod.rs:1082
     5:     0x7ff795a92ee4 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                                 at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\io\mod.rs:1514
     6:     0x7ff795a9b29b - std::sys_common::backtrace::_print
                                 at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\sys_common\backtrace.rs:61
     7:     0x7ff795a9b29b - std::sys_common::backtrace::print
                                 at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\sys_common\backtrace.rs:48
     8:     0x7ff795a9b29b - std::panicking::default_hook::{{closure}}
                                 at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panicking.rs:200
     9:     0x7ff795a9aed9 - std::panicking::default_hook
                                 at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panicking.rs:219
    10:     0x7ff795a9ba7f - std::panicking::rust_panic_with_hook
                                 at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panicking.rs:569
    11:     0x7ff795a9b5e5 - std::panicking::begin_panic_handler::{{closure}}
                                 at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panicking.rs:476
    12:     0x7ff795a985df - std::sys_common::backtrace::__rust_end_short_backtrace<closure-0,!>
                                 at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\sys_common\backtrace.rs:153
    13:     0x7ff795a9b599 - std::panicking::begin_panic_handler
                                 at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panicking.rs:475
    14:     0x7ff795aae060 - core::panicking::panic_fmt
                                 at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\core\src\panicking.rs:85
    15:     0x7ff795aade83 - core::option::expect_none_failed
                                 at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\core\src\option.rs:1221
    16:     0x7ff7959f5880 - core::result::Result<T,E>::unwrap::h4abe766c37c2e663
    17:     0x7ff7959f13f5 - build_script_main::find::probe_lua::hbc91469b81609887
    18:     0x7ff7959f4ff2 - <std::process::Command as build_script_main::CommandExt>::execute::{{closure}}::h5c4ffc21a23723af
    19:     0x7ff7959f36c6 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h43612d4e10ce1abd
    20:     0x7ff7959f3607 - std::sys_common::backtrace::__rust_begin_short_backtrace::he397c93ac43ec166
    21:     0x7ff7959f5c2c - std::rt::lang_start::{{closure}}::h56c7c24389f962f2
    22:     0x7ff795a9bc86 - core::ops::function::impls::{{impl}}::call_once
                                 at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\library\core\src\ops\function.rs:280
    23:     0x7ff795a9bc86 - std::panicking::try::do_call
                                 at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panicking.rs:373
    24:     0x7ff795a9bc86 - std::panicking::try
                                 at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panicking.rs:337
    25:     0x7ff795a9bc86 - std::panic::catch_unwind
                                 at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panic.rs:379
    26:     0x7ff795a9bc86 - std::rt::lang_start_internal
                                 at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\rt.rs:51
    27:     0x7ff7959f5c04 - std::rt::lang_start::h7b1072503172a0d1
    28:     0x7ff7959f5050 - main
    29:     0x7ff795ab3b60 - invoke_main
                                 at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
    30:     0x7ff795ab3b60 - __scrt_common_main_seh
                                 at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    31:     0x7ffa5b637034 - BaseThreadInitThunk
    32:     0x7ffa5cbfcec1 - RtlUserThreadStart

**Comment by flyinmind** [comment]
I found the problem.
Need to add "vendored" to features,  

[dependencies]
mlua = {version = "0.4", features = ["luajit", "**vendored**"]}
mlua_derive = "0.4"
