### ISSUE TITLE
`set_hook` causes panic

### ISSUE THREAD

**Issue by sxyazi** [khvzak/mlua#350]
```rust
fn main() {
	let lua = Lua::new();
	lua.set_hook(HookTriggers::EVERY_LINE, move |lua, _| {
		lua.remove_hook();
		Err("cancelled".into_lua_err())
	});

	let result: mlua::Result<()> = lua.load("print('xxx')").call(());
	println!("exit normally with:\n\n {:?}", result);
}
```

The code works fine in debug mode and prints out:

```
exit normally with:

 Err(CallbackError { traceback: "stack traceback:\n\t[string \"yazi-fm/src/main.rs:38:40\"]:1:in main chunk", cause: ExternalError("cancelled") })
```

However, in release mode with `panic = "abort"`, it will cause the program to crash instead of returning an error:

```
thread 'main' panicked at library/core/src/panicking.rs:155:5:
panic in a function that cannot unwind
stack backtrace:
   0: rust_begin_unwind
             at /rustc/bf8716f1cd6416266807706bcae0ecb2e51c9d4a/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_nounwind_fmt::runtime
             at /rustc/bf8716f1cd6416266807706bcae0ecb2e51c9d4a/library/core/src/panicking.rs:110:18
   2: core::panicking::panic_nounwind_fmt
             at /rustc/bf8716f1cd6416266807706bcae0ecb2e51c9d4a/library/core/src/panicking.rs:122:9
   3: core::panicking::panic_nounwind
             at /rustc/bf8716f1cd6416266807706bcae0ecb2e51c9d4a/library/core/src/panicking.rs:155:5
   4: core::panicking::panic_cannot_unwind
             at /rustc/bf8716f1cd6416266807706bcae0ecb2e51c9d4a/library/core/src/panicking.rs:241:5
   5: mlua::lua::Lua::set_thread_hook::hook_proc
   6: _lj_dispatch_ins
   7: _lj_vm_inshook
   8: _lua_pcall
   9: yazi::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread caused non-unwinding panic. aborting.
zsh: abort      cargo run --release
```

I want to know if there's any way to use `set_hook` with `panic = "abort"`.

If there's anything I can do to help, let me know. Thanks in advance!

**Comment by khvzak** [comment]
luajit relies on external unwinding for exception handling. If you compile with panic=abort you disable this mechanism. You can switch to a normal lua which uses setjmp/longjmp for exception handling.

**Comment by sxyazi** [comment]
I switched to Lua 5.4 and now everything works fine.

Thank you for the pointer and creating this awesome crate!
